JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60

ADMIN_USERNAME_ENV = "ADMIN_USERNAME"
ADMIN_PASSWORD_ENV = "ADMIN_PASSWORD"
JWT_SECRET_KEY_ENV = "JWT_SECRET_KEY"

INVALID_TOKEN_DETAIL = "Invalid or expired token."
INVALID_TOKEN_SUBJECT_DETAIL = "Invalid token subject."
MISSING_BEARER_TOKEN_DETAIL = "Missing bearer token."
