DEFAULT_SMTP_PORT = "587"
DEFAULT_SMTP_USE_TLS = "true"
EMAIL_SEND_TIMEOUT_SECONDS = 20

SMTP_HOST_ENV = "SMTP_HOST"
SMTP_USERNAME_ENV = "SMTP_USERNAME"
SMTP_PASSWORD_ENV = "SMTP_PASSWORD"
SMTP_PORT_ENV = "SMTP_PORT"
SMTP_USE_TLS_ENV = "SMTP_USE_TLS"
SMTP_FROM_EMAIL_ENV = "SMTP_FROM_EMAIL"
CONTACT_TO_EMAIL_ENV = "CONTACT_TO_EMAIL"

CONTACT_EMAIL_SUBJECT_PREFIX = "Portfolio contact request from"
CONTACT_EMAIL_HEADER = "New portfolio contact request"
CONTACT_EMAIL_SESSION_LABEL = "Session ID"
INVALID_SMTP_PORT_MESSAGE = "SMTP_PORT must be a number"
EMAIL_SEND_FAILURE_MESSAGE = "Failed to send contact email"
